# Generated by Django 4.1.7 on 2023-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortstories',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
